name: Deploy .NET Backend to Azure
#comment to trigger workflow
on:
  push:
    branches:
      - main
    # Triggers only when files inside the backend folder change
    paths:
      - 'SocialChat.backend/**' 

env:
  DOTNET_VERSION: '8.0.x'
  AZURE_WEBAPP_NAME: 'social-chat-api'
  # Targets the specific API project file, ignoring test layers
  PROJECT_PATH: './SocialChat.backend/SocialChat.Api/SocialChat.Api.csproj' 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build and Publish
        run: dotnet publish ${{ env.PROJECT_PATH }} --configuration Release --output ./publish_output

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish_output